server:
  undertow:
    max-http-post-size: -1B
    threads:
      io: 4
      worker: 40
    buffer-size: 1024
    direct-buffers: true
  port: 8761
eureka:
  instance:
    hostname: 127.0.0.1
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/