server:
  undertow:
    max-http-post-size: -1B
    threads:
      io: 4
      worker: 40
    direct-buffers: true
  port: 9080
  servlet:
    context-path: /account
spring:
  application:
    name: account-server
  zipkin:
    base-url: http://127.0.0.1:9411
    sender:
      type: web
    sleuth:
      sampler:
        probability: 1.0
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://127.0.0.1:3306/t_account
    username: root
    password: 19171567
    hikari:
      pool-name: account-hikari-mariadb
      minimum-idle: 5
      maximum-pool-size: 10
      idle-timeout: 180000
      max-lifetime: 180000
      auto-commit: true
      connection-timeout: 300000
      connection-test-query: SELECT 1
  mybatis:
    mapper-locations: classpath:mapper/*Mapper.xml
    configuration:
      map-underscore-to-camel-case: true
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: 123456
      client-name: lettuce
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka


